### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by jmuehlner**
These changes are to make this package python3-compatible, without breaking python2 compatibility.

### CODE REVIEW

**Comment by alvarop** [comment]
Thanks for the PR!

**Comment by jmuehlner** [comment]
Thanks for the quick response, @alvarop! Any chance we could get a release of these new changes soonish? :)

If not, I can create my own package for internal usage, but it'd be nice to stay on this upstream package if possible.

**Comment by alvarop** [comment]
Forgot about the pip repo! Changes should be up on pip now under version 0.2.1

**Comment by jmuehlner** [comment]
Amazing! Thank you!

**Pull request merged**
